CREATE CONSTRAINT law_id IF NOT EXISTS FOR (n:Law) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT part_id IF NOT EXISTS FOR (n:Part) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT chapter_id IF NOT EXISTS FOR (n:Chapter) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT section_id IF NOT EXISTS FOR (n:Section) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT article_id IF NOT EXISTS FOR (n:Article) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT article_code IF NOT EXISTS FOR (n:Article) REQUIRE n.article_code IS UNIQUE;
CREATE CONSTRAINT clause_id IF NOT EXISTS FOR (n:Clause) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT point_id IF NOT EXISTS FOR (n:Point) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT crime_id IF NOT EXISTS FOR (n:Crime) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT rule_id IF NOT EXISTS FOR (n:Rule) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT condition_id IF NOT EXISTS FOR (n:Condition) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT penalty_frame_id IF NOT EXISTS FOR (n:PenaltyFrame) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT penalty_id IF NOT EXISTS FOR (n:Penalty) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT legal_concept_id IF NOT EXISTS FOR (n:LegalConcept) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT aggravating_id IF NOT EXISTS FOR (n:AggravatingFactor) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT mitigating_id IF NOT EXISTS FOR (n:MitigatingFactor) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT subject_req_id IF NOT EXISTS FOR (n:SubjectRequirement) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT object_req_id IF NOT EXISTS FOR (n:ObjectRequirement) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT act_req_id IF NOT EXISTS FOR (n:ActRequirement) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT consequence_req_id IF NOT EXISTS FOR (n:ConsequenceRequirement) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT quantity_threshold_id IF NOT EXISTS FOR (n:QuantityThreshold) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT exception_id IF NOT EXISTS FOR (n:Exception) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT reference_id IF NOT EXISTS FOR (n:Reference) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT judicial_measure_id IF NOT EXISTS FOR (n:JudicialMeasure) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT slang_id IF NOT EXISTS FOR (n:SlangTerm) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT legal_signal_id IF NOT EXISTS FOR (n:LegalSignal) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT action_alias_id IF NOT EXISTS FOR (n:ActionAlias) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT substance_id IF NOT EXISTS FOR (n:Substance) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT substance_alias_id IF NOT EXISTS FOR (n:SubstanceAlias) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT scenario_fact_id IF NOT EXISTS FOR (n:ScenarioFact) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT matched_condition_id IF NOT EXISTS FOR (n:MatchedCondition) REQUIRE n.id IS UNIQUE;

CREATE FULLTEXT INDEX article_fulltext IF NOT EXISTS FOR (n:Article) ON EACH [n.title, n.full_text, n.normalized_text];
CREATE FULLTEXT INDEX clause_fulltext IF NOT EXISTS FOR (n:Clause) ON EACH [n.text, n.normalized_text];
CREATE FULLTEXT INDEX condition_fulltext IF NOT EXISTS FOR (n:Condition) ON EACH [n.text, n.normalized_text];
CREATE FULLTEXT INDEX crime_fulltext IF NOT EXISTS FOR (n:Crime) ON EACH [n.name, n.normalized_name];
CREATE FULLTEXT INDEX concept_fulltext IF NOT EXISTS FOR (n:LegalConcept) ON EACH [n.name, n.description, n.normalized_name];
